development:
  host: localhost
  database: tabelia_development

test:
  host: localhost
  database: tabelia_test

# set these environment variables on your prod server

production:
    hosts:
        -   -   server1-data.retocontinuo.local
            -   27017
        -   -   server2-data.retocontinuo.local
            -   27017
        -   -   server3-data.retocontinuo.local
            -   27017
    read_secondary: true
    username: tabelia
    password: 123456
    database: tabelia_production

productionold:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
