production:
    solr:
        hostname: server6.retocontinuo.local
        port: 8080
        log_level: WARNING

development:
    solr:
        hostname: 192.168.1.36
        port: 8983
        log_level: INFO      
      
test:
    solr:      
        hostname: server6.retocontinuo.local
        port: 8080
        log_level: WARNING